version: 0.2
env:
    variables:
        key: "value"
phases:
    install:
        runtime-versions:
            php: 7.3
        commands:
            -   |
                #Install composer
                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                php composer-setup.php ;
                php -r "unlink('composer-setup.php');" ;
                mv composer.phar /usr/local/bin/composer
    build:
        commands:
            - echo Build started on `date`
            - echo Installing composer deps
            - composer install
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Running JSONLint, PHPCS, PHPStan, PHPUnit
            - ./vendor/bin/jsonlint data/*.json
            - ./vendor/bin/phpcs src --standard=PSR2
            - ./vendor/bin/phpstan analyse src/ --level max
            - ./vendor/bin/phpunit
            - echo Tests completed on `date`